Delete alarm
DragonF0rm/LocationAlarm pull request #17
Opened 2020-01-08 07:15 UTC by bin-umar

2020-01-09 06:28 UTC, maksimuimin requested changes
**Баг:** В режим выделения можно попасть из режима выделения.
*Как воспроизвести:* создаём несколько точек, делаем длинный клик по одной точке, и короткий клик по другой точке (получаем selected=2 и 2 активных чекбокса), потом делаем длинный клик ещё по одной точке, получаем selected=1 и 2 активных чекбокса.
*Как должно быть:* в режиме выделения длинный клик не должен обрабатываться (или может рассматриваться как короткий клик)

**Баг:** MapFragment не обновляется, если на него смотреть.
*Как воспроизвесити:* Создаём будильник, выделяем его длинным кликом, переключаемся на вкладку Map, нажимаем кнопку удалить. При этом будильник удаляется, а маркер нет. Если переключиться на вкладку Alarms и обратно на Map, то маркер пропадёт.
*Как должно быть:* Маркер должен удаляться сразу при удалении будильника.
*Что делаем:* Как разберёшься с остальными проблемами, поставь таску на Леонида, пусть он пофиксит.

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/ActionBarCallBack.java
> +                Alarm alarm = viewModel.getAlarmLiveDataById(selectedItemId);
Отрефактори, пожалуйста, метод viewModel, он должен называться getAlarmById, это легаси

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/ActionBarCallBack.java
> +        listAdapter.notifyDataSetChanged();
Это лучше сделать методом listAdapter

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/AlarmListAdapter.java
> +    ActionMode actionMode;
Лучше приватные поля с доступом через методы

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/AlarmViewHolder.java
> +            selectItem(alarm.getId());
Аналогично, доступ лучше через метод

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/AlarmViewHolder.java
> +            title = "Select items";
Строковые константы вынести в ресурсы

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/res/layout/alarm_item.xml
> +    <CheckBox
У чекбокса выравнивание не по гайдлайнам, он должен быть выровнен по правому краю элемента списка с отступом, как у свитча

2020-01-09 06:28 UTC, DragonF0rm commented on app/src/main/res/layout/alarm_item.xml
> +        android:layout_height="42dp"
Размеры в ресурсы

2020-01-09 21:17 UTC, bin-umar commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/ActionBarCallBack.java
> +                Alarm alarm = viewModel.getAlarmLiveDataById(selectedItemId);
done

2020-01-09 21:18 UTC, bin-umar commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/ActionBarCallBack.java
> +        listAdapter.notifyDataSetChanged();
done

2020-01-09 21:18 UTC, bin-umar commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/AlarmListAdapter.java
> +    ActionMode actionMode;
done

2020-01-09 21:18 UTC, bin-umar commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/AlarmViewHolder.java
> +            selectItem(alarm.getId());
done

2020-01-09 21:18 UTC, bin-umar commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/alarm_list_fragment/AlarmViewHolder.java
> +            title = "Select items";
done

2020-01-09 21:23 UTC, bin-umar commented on app/src/main/res/layout/alarm_item.xml
> +    <CheckBox
done

2020-01-09 21:23 UTC, bin-umar commented on app/src/main/res/layout/alarm_item.xml
> +        android:layout_height="42dp"
done

2020-01-10 06:24 UTC, maksimuimin approved these changes
Поставь, пожалуйста, где-нибудь тудушник на второй баг (который про маркеры MapFragment), и можно мёрджить

2020-01-12 11:37 UTC, merged