address resolving
DragonF0rm/LocationAlarm pull request #18
Opened 2020-01-08 15:14 UTC by motychenkovLA

2020-01-09 17:05 UTC, maksimuimin requested changes
Посмотрел пр, в целом, заявленный функционал работает, но без саджестов очень больно. Я погуглил, у гугла есть инструменты для этого. Посмотри вот тут и попробуй реализовать, пожалуйста: https://developers.google.com/places/android-sdk/autocomplete?hl=ru

2020-01-09 17:05 UTC, maksimuimin commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/map_fragment/AddressProvider.java
> +            Address address = addresses.get(0);
Вот тут есть нюанс, если поставить точку, например, в океане, данный код всё равно найдёт её адрес - это будет страна, которой принадлежит данная територия. Ожидаемое поведение для таких случаев - выводить координаты вместо адреса. Я думаю, можно проверять наличиие почтового индекса или длину массива адресов чтобы понять, насколько адрес "существующий".

2020-01-09 17:05 UTC, maksimuimin commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/map_fragment/MapFragment.java
> +            if (mode != Mode.EDIT || lat == null || lon == null || activity == null) return;
Тут есть проблема. Если адрес не существует, то маркер не передвинется, а без саджестов шанс такого очень велик. Думаю, можно попробовать делать сплит адреса по разделитиелю (пробела и запятой должно хватаить) и искать с последовательным приближением. Но это надо тестить.

2020-01-09 17:05 UTC, maksimuimin commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/MainActivity.java
> +    }
Костыль, так по-хорошему быть не должно

2020-01-09 17:05 UTC, DragonF0rm commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/IMapFragmentActivity.java
> +}
Давай заменим на коллбек, который можно будет передавать в MapFragment, вместо того чтобы обязывать всех его возможных родителей реализовывать этот интерфейс, а то это не вяжется с концепцией его универсальности. Если вдруг возникают вопросы по реализации такого, гуглить в сторону "как передать люмбда-функцию как аргумент" и "функциональный интерфейс в java 8"

2020-01-10 21:19 UTC, motychenkovLA commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/map_fragment/AddressProvider.java
> +            Address address = addresses.get(0);
fixed. 
чекается количество адресов, как оказалось почтовый индекс не всегда есть в валидных местах и не всегда отсутствует посреди ничего.

2020-01-10 21:20 UTC, motychenkovLA commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/MainActivity.java
> +    }
fixed

2020-01-10 21:22 UTC, motychenkovLA commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/IMapFragmentActivity.java
> +}
в фрагмент нельзя засунуть колбек, сделал реализацию интерфейса необязательной.

2020-01-10 21:28 UTC, motychenkovLA commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/IMapFragmentActivity.java
> +}
в теории можно написать не анонимный сериализуемый колбек попробовать

2020-01-13 19:25 UTC, motychenkovLA commented on app/src/main/java/sleepless_nights/location_alarm/alarm/ui/map_fragment/MapFragment.java
> +            if (mode != Mode.EDIT || lat == null || lon == null || activity == null) return;
https://developers.google.com/places/android-sdk/usage-and-billing
есть небольшая проблема

2020-01-15 10:03 UTC, maksimuimin approved these changes

2020-01-15 10:03 UTC, merged